# docker-compose.base.yml
version: "3.9"
services:
  api_gateway:
    container_name: microns_api_gateway
    restart: always
    build: { context: ./api_gateway }
    ports:
      - "8001:80"
    volumes:
      - api_gateway_data:/var/www/html/storage
    networks: [BKnetwork]
  nginx:
    container_name: microns_nginx
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d # This will be mounted from the DOCKER_DIR
    networks: [BKnetwork]

volumes:
  api_gateway_data: null
networks:
  BKnetwork: null
